### ISSUE TITLE
Applying this code into Linux bash

### ISSUE THREAD

**Issue by yudhadimas** [kenogo/spotify-lyrics-cli#7]
Since I'm interested in this project, I really appreciate your work. Unfortunately, I don't implement this code into my Linux desktop because you wrote the instruction which are not understandable by people like me. Maybe I'm too new learning this project, but lemme know how to install it properly. I did all your unclear instruction such installing "request" and so on, but it seems that everything is not working flawlessly. Thanks a lot.

**Comment by kenogo** [comment]
What distro are you on? Ubuntu? This will help me a lot in answering your question. You should also tell me what commands you ran exactly, and what error you got, otherwise I can't know where you went wrong.

**Comment by kenogo** [comment]
I'll close this because it isn't really an issue with my software, but you can still ask questions here and I'll be answering.
